### ISSUE TITLE
Fatal error when using

### ISSUE THREAD

**Issue by philsbury** [nlemoine/timber-dump-extension#1]
Hi,

I'm receiving a fata error when I call dump:

`Fatal error: Uncaught Error: Call to undefined function Symfony\Component\VarDumper\Dumper\mb_convert_encoding() `

Any thoughts? 

Thanks
Phil

**Comment by nlemoine** [comment]
Hi @philsbury, 

Could you provide any information about your environment? This extension requires PHP >= 5.5.9.
Does your PHP installation have the `mbstring` extension?

**Comment by philsbury** [comment]
Hi @nlemoine, Thanks for coming back to me. 

`mbstring` was not installed, and my provisioner didn't do it either. Adding it manually has fixed it and all is awesome! 

Thank you!
Phil

**Comment by nlemoine** [comment]
Great!
