### ISSUE TITLE
In which folder should the composer command be run?

### ISSUE THREAD

**Issue by flip111** [nlemoine/timber-dump-extension#3]
The installation instructions are not quite clear to me

**Comment by flip111** [comment]
This directory seemed to work `wp-content/plugins/timber-library`, maybe add it to readme?

**Comment by nlemoine** [comment]
Any folder as long as you require the composer autoloader somewhere in your functions.php file or a plugin file.

This is a PHP package not intended to be used as Wordpress plugin. More as a composer dependency.

**Comment by BrettBedarf** [comment]
Will you elaborate any on requiring the composer autoloader? 

I composer installed and generated autoloader in my child theme root and then `require_once 'vendor/autoload.php';` in my child theme's functions.php

This resulted in `Fatal error: Uncaught Error: Class 'Twig_Loader_Filesystem' not found in .../wp-content/plugins/publishpress/common/php/class-module.php on line 54`

and pages no longer rendering.

Also, trying to composer install in the timber-library plugin as @flip111 suggested results in 
```
Fatal error: Uncaught Error: Class 'Timber\Timber' not found in  .../wp-content/plugins/timber-library/timber.php  on line 21

Error: Class 'Timber\Timber' not found in .../wp-content/plugins/timber-library/timber.php on line 21
```
