### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rkent-sgs** [nlemoine/timber-dump-extension#5]
I've installed the extension with composer but when I dump a variable it is unstyled
![image](https://user-images.githubusercontent.com/127872200/225049133-2a33325e-04db-4b0e-b482-31277210a07e.png)

**Comment by ThomasTheFourth** [comment]
I'm seeing the same issue.

**Comment by nlemoine** [comment]
Can one of you tell me more?

Where are you requiring the autoloader ?

**Comment by rkent-sgs** [comment]
in `functions.php`
